version: "3.8"

services:

  api:
    build: .
    image: restapi
    environment:
      - REDIS_HOST=redis-10821.c309.us-east-2-1.ec2.cloud.redislabs.com
      - REDIS_PORT=10821 
      - REDIS_PWD=BE1UW4XomabrdMNAQrcNf1hb1nuCDILb
    ports:
      - "8000:4000"
    networks:
      - backend
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:alpine
    networks:
      - backend

  cli:
    build: .
    image: restapi_cli
    command: ["python", "/app/restAPI_cli.py"]
    depends_on:
      - api 
    networks:
      - backend

  testrunner:
    volumes:
      - .:/app
    build: . 
    command: ["sh", "-c", "pip install pytest && pytest -s testcode.py"]
    depends_on:
     - api  
    networks:
     - backend

  pipeline:
    build: .
    image: pipeline
    command: ["python", "/app/pipeline.py"]
    depends_on:
      - api 
    networks:
      - backend

networks:
  backend: