version: "3.8"

services:

  api:
    build: .
    image: restapi
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379 
    ports:
      - "8000:4000"
    networks:
      - backend
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:alpine
    networks:
      - backend

  cli:
    build: .
    image: restapi_cli
    command: ["python", "/app/restAPI_cli.py"]
    depends_on:
      - api 
    networks:
      - backend

  testrunner:
    volumes:
      - .:/app
    ports:
      - "8000:4000"
    build: . 
    command: ["sh", "-c", "pip install pytest && pytest -s testcode.py"]
    depends_on:
     - api  
    networks:
     - backend

networks:
  backend: