name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    paths:  
      - "restAPI/**"
      
  pull_request:
    branches: [ "main" ]
    paths:   
      - "restAPI/**"

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3

    - name: Start stack  
      run: docker-compose up -d

    - name: Run API
      run: docker-compose exec api python restAPI.py

    - name: Login to Docker Hub
     uses: docker/login-action@v1
     with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push image 
      run: |
        docker-compose build
        docker tag restapi $DOCKER_USERNAME/restapi:latest  
        docker push $DOCKER_USERNAME/restapi:latest