name: CI/CDs

on:
  push:
    branches: [ "main" ]
    paths:
      - "restAPI/**"

  pull_request:
    branches: [ "main" ] 
    paths:
      - "restAPI/**"

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build containers
      run: docker-compose build
    
    - name: Run API tests
      run: docker-compose exec api python restAPI.py

    - name: Login to Docker Hub  
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    # Push to Docker Hub

    - name: Build and push image 
      run: |
        docker-compose build
        docker tag restapi $DOCKER_USERNAME/restapi:latest  
        docker push $DOCKER_USERNAME/restapi:latest
