name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name:  Build containers
      run: docker-compose build

    - name: Run API tests
      run: docker-compose run api python testcode.py
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag and push API image  
      run: |
        docker tag restapi ${{ secrets.DOCKERHUB_USERNAME }}/restapi:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/restapi:latest
