name: CI/CD Pipeline 

on:
  push:
    branches: [ "main" ]
    paths:  
      - "restAPI/**"

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build API image  
      run: docker build -t myapi .

    - name: Run container
      run: docker run -d myapi  

    - name: Run API tests   
      run: docker exec myapi python /code/testcode.py