name: CI/CD Pipeline 

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3

    - name: Build image
      run: |
        docker-compose build
        docker tag restapi myimage:latest
    
    - name: Start stack
      run: docker-compose up -d

    - name: Run tests
      run: |
        pytest -s testcode.py
      shell: bash

  
    