name: Build and Test

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Start stack
      run: docker-compose up -d

    - name: Test API
      run: docker-compose exec api python restAPI.py

    - name: Build image
      run: |
        docker-compose build
        docker tag restapi myimage:latest
