name: CI/CD Pipeline 

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest python-dotenv

    - name: Build image
      run: |
        docker-compose build
        docker tag restapi myimage:latest
    
    - name: Start stack
      run: docker-compose up -d

    - name: Set API_URL
      run: echo "API_URL= http://34.174.43.161">> $GITHUB_ENV

    
    